[General]
autodetectLanguage=true
backgroundCheckerEnabled=true
checkUppercase=true
checkerEnabledByDefault=true
defaultClient=
defaultLanguage=en_US
preferredLanguages=@Invalid()
skipRunTogether=true
